version: '3'
services:
  web:
    image: nginx
    ports:
     - "7070:80"
    volumes:
      - ./src/web/html:/usr/share/nginx/html
  api:
    image: nginx
    ports:
     - "9090:80"
    volumes:
      - ./src/api/html:/usr/share/nginx/html
  proxy:
    image: nginx
    ports:
      - "5050:80"
    volumes:
      - ./src/proxy/conf:/etc/nginx/conf.d
